import type { ResolvedManifest, Word } from "@vb/engine/schema";

/** Default props so Remotion Studio opens without a project. Audio paths are empty → skipped. */
const text = "Your database is slow because it's reading every single row.";
const words: Word[] = text.split(" ").map((t, i) => ({
  text: t,
  i,
  start: i * 0.32,
  end: i * 0.32 + 0.28,
  startFrame: Math.round(i * 0.32 * 30),
  endFrame: Math.round((i * 0.32 + 0.28) * 30),
  emphasis: ["every", "single", "row."].includes(t),
}));

export const SAMPLE: ResolvedManifest = {
  version: 1,
  slug: "sample",
  title: "Sample",
  fps: 30,
  width: 1080,
  height: 1920,
  durationInFrames: 120,
  theme: "midnight",
  voice: "af_heart",
  music: null,
  brand: { handle: "@DummySticky", name: "Dummy Sticky" },
  scenes: [
    {
      id: "hook",
      speech: text,
      isClip: false,
      clipVolume: 1,
      startFrame: 0,
      durationInFrames: 120,
      speechFrames: 105,
      audioSrc: "",
      words,
      layout: "character_bottom",
      transition: "cut",
      captions: true,
      speaker: null,
      captionStyle: "normal",
      bare: false,
      character: {
        id: "narrator",
        style: "stickman",
        pose: "explaining",
        expression: "neutral",
        position: "center",
      scale: 1,
        poseChanges: [
          { pose: "shocked", expression: "surprised", atFrame: 30 },
          { pose: "pointing_up", atFrame: 66 },
        ],
        shots: [],
        strikes: [],
        throws: [],
        entrance: null,
        exit: null,
        travel: null,
        jump: null,
      },
      extras: [],
      props: [{ name: "database", atFrame: 10, untilFrame: 120, anim: "pop", position: "top", scale: 1, exit: "fade" }],
      sfx: [],
      bubbles: [{ text: "?!", atFrame: 32, untilFrame: 70, side: "right" }],
      camera: [{ move: "punch_in", atFrame: 30 }],
      overlays: [],
    },
  ],
  meta: { resolvedAt: "", engineVersion: "0", ttsModel: "", manifestHash: "" },
};
