import { z } from "zod";
import {
  CAMERA_MOVES,
  CHARACTER_STYLES,
  EXPRESSIONS,
  LAYOUTS,
  POSES,
  POSITIONS,
  PROPS,
  PROP_ANIMS,
  PROP_POSITIONS,
  SFX,
  THEMES,
  TRANSITIONS,
  VOICES,
  OVERLAYS,
} from "./catalog.js";

/**
 * The compiled manifest. Every anchor is now an absolute frame number and every
 * scene has audio + word timings. This is the ONLY thing the renderer reads.
 * Generated by the resolver — never hand-edited.
 */

export const Word = z.object({
  text: z.string(),
  /** Index into the scene's token list. */
  i: z.number().int(),
  /** Seconds, relative to the scene's audio clip. */
  start: z.number(),
  end: z.number(),
  /** Absolute frames in the composition timeline. */
  startFrame: z.number().int(),
  endFrame: z.number().int(),
  emphasis: z.boolean(),
});
export type Word = z.infer<typeof Word>;

export const ResolvedPoseChange = z.object({
  pose: z.enum(POSES),
  expression: z.enum(EXPRESSIONS).optional(),
  atFrame: z.number().int(),
});

export const ResolvedProp = z.object({
  name: z.enum(PROPS),
  atFrame: z.number().int(),
  untilFrame: z.number().int(),
  anim: z.enum(PROP_ANIMS),
  position: z.enum(PROP_POSITIONS),
  scale: z.number(),
  exit: z.enum(["fade", "cut", "burst"]).default("fade"),
});

export const ResolvedSfx = z.object({
  name: z.enum(SFX),
  atFrame: z.number().int(),
  volume: z.number(),
  /** Path relative to renderer/public. */
  src: z.string(),
});

export const ResolvedBubble = z.object({
  text: z.string(),
  atFrame: z.number().int(),
  untilFrame: z.number().int(),
  side: z.enum(["left", "right"]).default("right"),
  on: z.string().optional(),
});

export const ResolvedExtra = z.object({
  id: z.string(),
  style: z.enum(CHARACTER_STYLES),
  color: z.string().optional(),
  pose: z.enum(POSES),
  expression: z.enum(EXPRESSIONS),
  /** Centre x in px; travel overrides over its window. */
  x: z.number(),
  scale: z.number(),
  travel: z.object({ fromX: z.number(), toX: z.number(), startFrame: z.number().int(), endFrame: z.number().int() }).nullable(),
  poseChanges: z.array(ResolvedPoseChange),
  /** Absolute frame the character is knocked flat (from knockedOutAt or a throw hit). */
  koFrame: z.number().int().nullable(),
  fallDir: z.enum(["left", "right"]).nullable().default(null),
  label: z.string().nullable().default(null),
  held: z.enum(["frying_pan", "ball"]).nullable().default(null),
  heldFrame: z.number().int().default(0),
});
export type ResolvedExtra = z.infer<typeof ResolvedExtra>;

export const ResolvedProjectile = z.object({
  from: z.string(),
  to: z.string(),
  atFrame: z.number().int(),
  hitFrame: z.number().int(),
  outcome: z.enum(["hit", "miss", "deflect", "roll"]),
  /** Barrage index, for deterministic variation. */
  n: z.number().int(),
});

export const ResolvedThrow = z.object({
  atFrame: z.number().int(),
  item: z.literal("batarang"),
  /** One entry per hop: target id ("camera" allowed) and the frame it lands. */
  hops: z.array(z.object({ target: z.string(), hitFrame: z.number().int() })),
});

export const ResolvedCamera = z.object({
  move: z.enum(CAMERA_MOVES),
  atFrame: z.number().int(),
});

export const ResolvedOverlay = z.object({
  kind: z.enum(OVERLAYS),
  atFrame: z.number().int(),
  untilFrame: z.number().int(),
  text: z.string().optional(),
});

export const ResolvedShot = z.object({ atFrame: z.number().int(), big: z.boolean(), camera: z.boolean().default(false) });
export const ResolvedStrike = z.object({ atFrame: z.number().int(), target: z.enum([...PROP_POSITIONS, "camera"]), big: z.boolean() });

export const ResolvedScene = z.object({
  id: z.string(),
  speech: z.string(),
  /** True when the audio is a pre-recorded clip rather than TTS. */
  isClip: z.boolean().default(false),
  clipVolume: z.number().default(1),
  startFrame: z.number().int(),
  durationInFrames: z.number().int(),
  /** Speech-only length (excludes pauseAfter), frames. */
  speechFrames: z.number().int(),
  /** Path relative to renderer/public (staticFile). */
  audioSrc: z.string(),
  words: z.array(Word),
  layout: z.enum(LAYOUTS),
  transition: z.enum(TRANSITIONS),
  captions: z.boolean().default(true),
  speaker: z.string().nullable().default(null),
  captionStyle: z.enum(["normal", "beat"]).default("normal"),
  bare: z.boolean().default(false),
  character: z
    .object({
      id: z.string(),
      style: z.enum(CHARACTER_STYLES),
      color: z.string().optional(),
      pose: z.enum(POSES),
      expression: z.enum(EXPRESSIONS),
      position: z.enum(POSITIONS),
      scale: z.number().default(1),
      poseChanges: z.array(ResolvedPoseChange),
      shots: z.array(ResolvedShot).default([]),
      strikes: z.array(ResolvedStrike).default([]),
      throws: z.array(ResolvedThrow).default([]),
      entrance: z.object({ atFrame: z.number().int(), landFrame: z.number().int() }).nullable().default(null),
      exit: z.object({ atFrame: z.number().int(), endFrame: z.number().int() }).nullable().default(null),
      jump: z
        .object({
          atFrame: z.number().int(),
          crouchFrames: z.number().int(),
          airFrames: z.number().int(),
          landFrames: z.number().int(),
          settleFrames: z.number().int(),
          fromX: z.number(),
          toX: z.number(),
          height: z.number(),
        })
        .nullable()
        .default(null),
      /** Pixel x of the character rect's left edge over [startFrame, endFrame]. */
      travel: z
        .object({ fromX: z.number(), toX: z.number(), startFrame: z.number().int(), endFrame: z.number().int() })
        .nullable()
        .default(null),
    })
    .nullable(),
  extras: z.array(ResolvedExtra).default([]),
  props: z.array(ResolvedProp),
  sfx: z.array(ResolvedSfx),
  bubbles: z.array(ResolvedBubble),
  camera: z.array(ResolvedCamera),
  overlays: z.array(ResolvedOverlay).default([]),
  projectiles: z.array(ResolvedProjectile).default([]),
});
export type ResolvedScene = z.infer<typeof ResolvedScene>;

export const ResolvedManifest = z.object({
  version: z.literal(1),
  slug: z.string(),
  title: z.string(),
  fps: z.number().int(),
  width: z.number().int(),
  height: z.number().int(),
  durationInFrames: z.number().int(),
  theme: z.enum(THEMES),
  voice: z.enum(VOICES),
  music: z
    .object({
      src: z.string(),
      volume: z.number(),
    })
    .nullable(),
  scenes: z.array(ResolvedScene),
  /** Channel handle drawn as a watermark on every frame; null = none. */
  brand: z.object({ handle: z.string(), name: z.string() }).nullable().default(null),
  /** Provenance for reproducibility. */
  meta: z.object({
    resolvedAt: z.string(),
    engineVersion: z.string(),
    ttsModel: z.string(),
    manifestHash: z.string(),
  }),
});
export type ResolvedManifest = z.infer<typeof ResolvedManifest>;
